services:
  mongo:
    image: mongo:6.0
    container_name: cloudservice-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cloudservice
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  cloud-service:
    build: .
    container_name: cloud-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: CloudService
      SPRING_DATA_MONGODB_URI: mongodb://admin:secret@mongo:27017/cloudservice?authSource=admin
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
    depends_on:
      - mongo

volumes:
  mongo_data:
